securityContext:
  enabled: false

## Set default accesskey, secretkey
##
accessKey:
  password: "minio"
secretKey:
  password: "minio123"

## Use existing pv-claim
##
persistence:
  existingClaim: "argo-minio"

## Create a bucket after minio install
##
defaultBucket:
  enabled: true
  ## If enabled, must be a string with length > 0
  name: "argo-minio"
  ## Can be one of none|download|upload|public
  policy: none
  ## Purge if bucket exists already
  purge: false


image:
  tag: 2021.6.17-debian-10-r71